config/routes.rb
Rails.application.routes.draw do
  get 'users/index'
  get 'users/show'
  get 'users/edit'
  get 'pages/secret'
  resources :posts
  resources :users
  root to:'posts#index'

  get '/login'     => 'sessions#new'
  post '/login'    => 'sessions#create'
  get '/logout' => 'sessions#destroy'  

  post '/posts/confirm' => 'posts#confirm'
  post '/posts/updateConfirm' => 'posts#updateConfirm'
  post '/posts/update' => 'posts#update'
  delete '/posts/destroy' => 'posts#destroy'
  get '/search' => 'posts#search'

  get '/users' =>'users#index'
  post '/users/confirm' => 'users#confirm'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/post.rb
class Post < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password

    has_many :post

    # validates :password, confirmation: true
    # validates :password_confirmation, presence: true

    # validates :email, presence: true, uniqueness: true
    # validates_presence_of :name,:message => "Please Provide User Name"

    self.inheritance_column = :_type_disabled

    before_create {generate_token(:auth_token)}

    def generate_token(column)
        begin
            self[column] = SecureRandom.urlsafe_base64
        end while User.exists?(column => self[column])
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user

    def current_user
        # @current_user ||= User.find_by_auth_token!(cookies[:auth_token]) if cookies[:auth_token]
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end

    def authorize
        redirect_to login_path, alert: 'You must be logged in to access this page.' if current_user.nil?
      end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  # Restrict access so only logged in users can access the secret page:
  before_action :authorize, only: [:index]

  def secret
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :redirect_cancel, only: [:create, :update]
  before_action :authorize, only: [:index, :edit, :new, :create]

  def index
    @posts = Post.find_by_sql("SELECT u1.name AS c_name, u2.name AS u_name, p.* FROM posts p JOIN users u1 ON
       u1.id = p.create_user_id JOIN users u2 ON u2.id = p.updated_user_id;")
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
  end

  def confirm
    @post = Post.new(params.require(:post).permit(:title, :description))
    render :create
  end

  def create
    post = Post.new(params.require(:post).permit(:title, :description))
    post.status = 1
    post.create_user_id = session[:user_id]
    post.updated_user_id = session[:user_id]
    post.save
    redirect_to root_path
  end

  def edit
    @post = Post.find(params[:id])
    $post_id = @post.id
  end

  def updateConfirm
    @post = Post.new(post_params)
    render :update
  end


  def update
    post = Post.find($post_id)
    post.updated_user_id = session[:user_id]
    post.update(post_params)
    flash[:notice] = "Post sucessfully edited."
    redirect_to root_path
  end

  def post_params
    params.require(:post).permit(:title, :description, :status)
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    redirect_to root_path
  end

  def redirect_cancel
    redirect_to root_path if params[:cancel]
  end

  def search
    if params[:search].blank?
      redirect_to root_path and return
    else
      @parameter = params[:search].downcase
      result = Post.all.where("lower(title) OR lower(description) LIKE :search", search: "%#{@parameter}%")
      post_by_sql = Post.find_by_sql("SELECT users.name, posts.* FROM users INNER JOIN 
        posts ON posts.create_user_id = users.id where posts.status = 1")
        binding.break
        if result.title == post_by_sql.title
          redirect_to root_path
        end
      # render :index
    end
  end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def create
        user = User.find_by(email: params[:login][:email].downcase)

        if user && user.authenticate(params[:login][:password])
            session[:user_id] = user.id.to_s
            redirect_to root_path
        else
            flash.now.alert = "Incorrect Email or Password!!!"
            render :new
        end
    end

    def destroy
        session.delete(:user_id)
        redirect_to login_path
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # before_action :redirect_cancel, only: [:create, :update]
  before_action :authorize, only: [:index, :edit, :new, :create]

    def new
        @user = User.new
    end

    def index
        @user = User.all
    end

    def confirm
        @user = User.new(params.require(:user).permit(:name, :email, :password, :password_confirmation, :type, :phone, :dob, :address, :profile))
        render :create
    end

    def create
      user = User.new(params.require(:user).permit(:name, :email, :password, :type, :phone, :dob, :address, :profile))
      user.create_user_id = session[:user_id]
      user.updated_user_id = session[:user_id]
      user.save
      redirect_to '/users'
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css" rel="stylesheet">
<link href="https://gitcdn.github.io/bootstrap-toggle/2.2.2/css/bootstrap2-toggle.min.css" rel="stylesheet">
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.min.js"
  integrity="sha384-Atwg2Pkwv9vp0ygtn1JAojH0nYbwNJLPhwyoVbhoPwBhjQPR5VtM2+xf0Uwh9KtT" crossorigin="anonymous"></script>
<script src="https://gitcdn.github.io/bootstrap-toggle/2.2.2/js/bootstrap2-toggle.min.js"></script>

<!-- For Datatable -->
<link rel="stylesheet" href="https://cdn.datatables.net/1.11.5/css/jquery.dataTables.min.css">
<script src="https://code.jquery.com/jquery-3.5.1.js"></script>
<script src="https://cdn.datatables.net/1.11.5/js/jquery.dataTables.min.js"></script>

<%= stylesheet_link_tag 'slider.css' %>
<%= stylesheet_link_tag 'style.css' %>

<body class="d-flex flex-column min-vh-100">
  <% if alert %>
  <div class="alert alert-danger" role="alert">
    <%= alert %>
  </div>
  <% end %>
  <header>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="#">Bulletin_Board</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <%= link_to 'Users', "/users", class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Posts", "/posts", class: "nav-link" %>
          </li>
          <li class="nav-item right-side">
            <%= link_to "Create User", "/users/new", class: "nav-link" %>
          </li>
          <li class="nav-item dropdown right-side">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown"
              aria-haspopup="true" aria-expanded="false">
              <% if current_user %>
              <%= "#{current_user.name}" %>
              <% end %>
              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                class="bi bi-person-lines-fill" viewBox="0 0 16 16">
                <path d="M6 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6zm-5 6s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1H1zM11
                   3.5a.5.5 0 0 1 .5-.5h4a.5.5 0 0 1 0 1h-4a.5.5 0 0 1-.5-.5zm.5 2.5a.5.5 0 0 0 0
                    1h4a.5.5 0 0 0 0-1h-4zm2 3a.5.5 0 0 0 0 1h2a.5.5 0 0 0 0-1h-2zm0 3a.5.5 0 0 0 0
                     1h2a.5.5 0 0 0 0-1h-2z" />
              </svg>
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="#">Profile</a>
              <%= link_to 'Logout', logout_path, method: :delete, class: 'dropdown-item' %>
            </div>
          </li>
        </ul>
      </div>
    </nav>
  </header>

  <% if notice %>
  <div class="alert alert-success alert-pos" role="alert">
    <%= notice %>
  </div>
  <% end %>

  <div class="jumbotron vertical-center">
      <%= yield %>
  </div>

  <footer class="mt-auto">
    <div class="p-4 bg-light row">
      <div class="col-7">
        <a class="text-reset fw-bold text-decoration-none" target="blank"
          href="https://seattleconsultingmyanmar.com/">Seattle Consulting Myanmar</a>
      </div>
      <div class="col-5">
        <span class="float-right">
          Copyright &copy; Seattle Consulting Myanmar Co., Ltd. All rights reserved.
        </span>
      </div>
    </div>
  </footer>
</body>

</html>

app/views/layouts/header.html.erb
<nav class="navbar navbar-light bg-light">
  <a class="navbar-brand" href="#">Bulletin_Board</a>
</nav>

app/views/pages/secret.html.erb
<h1>Pages#secret</h1>
<p>Find me in app/views/pages/secret.html.erb</p>

app/views/posts/_delete_modal.html.erb
<style>
  .f-17 {
    font-size: 17px;
  }
</style>
<h3>Are you sure to delete post?</h3>
<dl class="row f-17">
  <dt class="col-sm-6">ID</dt>
  <dd class="col-sm-6"><%= post.id %></dd>
  <dt class="col-sm-6">Title</dt>
  <dd class="col-sm-6"><%= post.title %></dd>
  <dt class="col-sm-6">Description</dt>
  <dd class="col-sm-6"><%= post.description %></dd>
  <dt class="col-sm-6">Status</dt>
  <dd class="col-sm-6">
    <% if post.status == 0 %>
    Inactive
    <% elsif post.status == 1 %>
    Active
    <% end %>
  </dd>
</dl>

app/views/posts/_show_modal.html.erb
  <dl class="row">
    <dt class="col-sm-6">Title</dt>
    <dd class="col-sm-6"><%= post.title %></dd>
    <dt class="col-sm-6">Description</dt>
    <dd class="col-sm-6"><%= post.description %></dd>
    <dt class="col-sm-6">Status</dt>
    <dd class="col-sm-6">
      <% if post.status == 0 %>
        Inactive
      <% elsif post.status == 1 %>
        Active
      <% end %>
    </dd>
    <dt class="col-sm-6">Created Date</dt>
    <dd class="col-sm-6"><%= post.created_at.strftime('%F').gsub('-', '/') %></dd>
    <dt class="col-sm-6">Created User</dt>
    <dd class="col-sm-6"><%= post.c_name %></dd>
    <dt class="col-sm-6">Updated Date</dt>
    <dd class="col-sm-6"><%= post.updated_at.strftime('%F').gsub('-', '/') %></dd>
    <dt class="col-sm-6">Updated User</dt>
    <dd class="col-sm-6"><%= post.u_name %></dd>
  </dl>

app/views/posts/create.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="main-content w-75">
      <h3>Create Post</h3>
      <div class="row">
        <div class="col-sm-3"></div>
        <div class="col-sm-6">
          <%= form_with(model: @post, local: true) do |form| %>
          <div class="form-group row mb-4">
            <%= form.label :title, class: 'col-md-4 col-form-label' %>
            <div class="col-md-8">
              <%= form.text_field :title, disabled: true, class: 'form-control' %>
            </div>
          </div>

          <div class="form-group row mb-4">
            <%= form.label :description, class: 'col-md-4 col-form-label' %>
            <div class="col-md-8">
              <%= form.text_area :description, disabled: true, class: 'form-control text-area' %>
            </div>
          </div>

          <div class="form-group row mb-4">
            <div class="col-md-4"></div>
            <div class="col-md-2 me-3">
              <%= form.submit "Confirm", class: 'btn btn-success' %>
            </div>
            <div class="col-md-2">
              <%= link_to 'Cancel', 'javascript:history.back()', :class => "btn btn-secondary" %>
            </div>
          </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/posts/edit.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="main-content w-75">
      <h3>Edit Post</h3>
      <div class="row">
        <div class="col-sm-3"></div>
        <div class="col-sm-6">
          <%= form_with scope: :post, url: "/posts/updateConfirm", local: true do |form| %>
          <div class="form-group row mb-4">
            <%= form.label :title, class: 'col-md-4 col-form-label' %>
            <div class="col-md-8">
              <%= form.text_field :title, class: 'form-control', id: 'title' %>
            </div>
          </div>

          <div class="form-group row mb-4">
            <%= form.label :description, class: 'col-md-4 col-form-label' %>
            <div class="col-md-8">
              <%= form.text_area :description, class: 'form-control text-area' %>
            </div>
          </div>

          <div class="form-group row mb-4">
            <%= form.label :status, class: 'col-md-4 col-form-label' %>
            <div class="col-md-8">
              <label class="switch">
                <%= form.check_box :status %>
                <span class="slider round"></span>
              </label>
            </div>
          </div>

          <div class="form-group row mb-4">
            <div class="col-md-4"></div>
            <div class="col-md-2">
              <%= form.submit "Edit", class: 'btn btn-success' %>
            </div>
            <div class="col-md-2">
            <input type="button" onclick="reset()" value="Reset" class="btn btn-secondary">
            </div>
          </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<body>
  <div class="container">
    <div class="row justify-content-center">
      <div class="main-content">
        <h3>Post List</h3>
        <div class="d-flex flex-row-reverse">
          <div class="p-2">
            <div class="col-md-12">
              <%= link_to 'Download', new_post_path, class: "btn btn-success" %>
            </div>
          </div>
          <div class="p-2">
            <div class="col-md-12">
              <%= link_to 'Upload', new_post_path, class: "btn btn-success" %>
            </div>
          </div>
          <div class="p-2">
            <div class="col-md-12">
              <%= link_to 'Create', new_post_path, class: "btn btn-success" %>
            </div>
          </div>
          <div class="p-2">
            <%= form_tag(search_path, :method => "get") do %>
            <div class="row">
              <div class="col-auto">
                <label class="col-form-label">Keyword:</label>
              </div>
              <div class="col-auto">
                <%= search_field_tag :search, params[:search], class: "form-control" %>
              </div>
              <div class="col-auto">
                <%= button_tag "Search", class: "btn btn-success" %>
              </div>
            </div>
            <% end %>
          </div>
        </div>
        <div class="scrollme">
          <table id="post-table" class="table table-responsive my-tab display">
            <thead class="thead-custom">
              <tr>
                <th>Post Title</th>
                <th>Post Description</th>
                <th>Posted User</th>
                <th>Posted Date</th>
                <th>Operation</th>
              </tr>
            </thead>
            <tbody>
              <% @posts.each do |post| %>
              <tr>
                <td> <%= link_to (post.title), "#detailModal-#{post.id}", 'data-bs-toggle' => 'modal',
                class: "text-decoration-none text-reset" %> </td>
                <td> <%= post.description %></td>
                <td><%= post.c_name %></td>
                <td> <%= post.created_at.strftime('%F').gsub('-', '/') %> </td>
                <td>
                  <%= link_to "Edit", edit_post_path(post.id), method: :get, class: 'btn btn-primary' %>
                  <%= link_to "Delete", "#deleteModal-#{post.id}", 'data-bs-toggle' => 'modal',
                  class: 'btn btn-danger'  %>
                </td>
              </tr>
              <div class="modal" id="detailModal-<%= post.id %>">
                <div class="modal-dialog">
                  <div class="modal-content">

                    <!-- Modal Header -->
                    <div class="modal-header">
                      <h4 class="modal-title">Post Detail</h4>
                      <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
                    </div>

                    <!-- Modal body -->
                    <div class="modal-body">
                      <%= render :partial => 'show_modal', :locals => { :post => post } %>
                    </div>

                    <!-- Modal footer -->
                    <div class="modal-footer">
                      <button type="button" class="btn btn-danger" data-bs-dismiss="modal">Close</button>
                    </div>

                  </div>
                </div>
              </div>

              <div class="modal" id="deleteModal-<%= post.id %>">
                <div class="modal-dialog">
                  <div class="modal-content">

                    <!-- Modal Header -->
                    <div class="modal-header">
                      <h4 class="modal-title">Delete Confirm</h4>
                      <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
                    </div>

                    <!-- Modal body -->
                    <div class="modal-body">
                      <%= render :partial => 'delete_modal', :locals => { :post => post } %>
                    </div>

                    <!-- Modal footer -->
                    <div class="modal-footer">
                      <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                      <%= button_to 'Delete', post_path(post.id), method: :delete, class: 'btn btn-danger' %>
                    </div>

                  </div>
                </div>
              </div>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</body>
<script type="text/javascript">
  $(document).ready(function () {
    $('#post-table').DataTable({
      "pagingType": "simple_numbers",
      "pageLength": 5,
      "ordering": false,
      "info": false,
      "lengthChange": false,
      "bFilter": false,
      "scrollCollapse": true
    })
  });
</script>

app/views/posts/new.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="main-content w-75">
      <h3>Create Post</h3>
      <div class="row">
        <div class="col-sm-3"></div>
        <div class="col-sm-6">
          <%= form_with scope: :post, url: "/posts/confirm", local: true do |form| %>
          <div class="form-group row mb-4">
            <%= form.label :title, class: 'col-md-4 col-form-label' %>
            <div class="col-md-8">
              <%= form.text_field :title, class: 'form-control' %>
            </div>
          </div>

          <div class="form-group row mb-4">
            <%= form.label :description, class: 'col-md-4 col-form-label' %>
            <div class="col-md-8">
              <%= form.text_area :description, class: 'form-control text-area' %>
            </div>
          </div>

          <div class="form-group row mb-4">
            <div class="col-md-4"></div>
            <div class="col-md-2 me-2">
              <%= form.submit "Create", class: 'btn btn-success' %>
            </div>
            <div class="col-md-2">
              <%= submit_tag("Clear", { :name => 'reset', :id => 'reset_button', :type => "reset", :class => 'btn btn-secondary'}) %>
            </div>
          </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/posts/search.html.erb
<%= @result.each do |rslt| %>
<%= rslt.title %> <br>
<% end %>

app/views/posts/show.html.erb
<%= render "remote_modal", title: "New item" do %>

  <%= render "form", post: @post %>

<% end %>

app/views/posts/update.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="main-content w-75">
      <h3>Edit Post</h3>
      <div class="row">
        <div class="col-sm-3"></div>
        <div class="col-sm-6">
          <%= form_with scope: :post, url: "/posts/update", local: true do |form| %>
          <div class="form-group row mb-4">
            <%= form.label :title, class: 'col-md-4 col-form-label' %>
            <div class="col-md-8">
              <%= form.text_field :title, readonly: true, class: 'form-control' %>
            </div>
          </div>

          <div class="form-group row mb-4">
            <%= form.label :description, class: 'col-md-4 col-form-label' %>
            <div class="col-md-8">
              <%= form.text_area :description, readonly: true, class: 'form-control text-area' %>
            </div>
          </div>

          <div class="form-group row mb-4">
            <%= form.label :status, class: 'col-md-4 col-form-label' %>
            <div class="col-md-8">
              <label class="switch">
                <%= form.check_box :status, disabled: true %>
                <span class="slider round op"></span>
              </label>
            </div>
          </div>

          <div class="form-group row mb-4">
            <div class="col-md-4"></div>
            <div class="col-md-3">
              <%= form.submit "Confirm", class: 'btn btn-success' %>
            </div>
            <div class="col-md-3">
              <%= link_to 'Cancel', 'javascript:history.back()', :class => "btn btn-secondary" %>
            </div>
          </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/create.html.erb
<div class="container">
  <div class="row justify-content-md-center">
    <div class="col-6">
      <%= form_with(model: @user, local: true) do |form| %>
      <div class="form-group">
        <%= form.label :Name %>
        <%= form.text_field :name, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= form.label :'E-mail address' %>
        <%= form.text_area :email, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= form.label :Password %>
        <%= form.password_field :password, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= form.label :'Password confirmation' %>
        <%= form.password_field :passwordConfirmation, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= form.label :Type %>
        <%= form.text_field :type, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= form.label :Phone %>
        <%= form.text_field :phone, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= form.label :'Date of birth' %>
        <%= form.text_field :dob, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= form.label :Address %>
        <%= form.text_field :address, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= form.label :Profile %>
        <%= form.text_field :profile, class: 'form-control' %>
      </div>
      <div class="form-group d-inline">
        <%= form.submit "Confirm", class: 'btn btn-primary' %>
      </div>
      <div class="form-group d-inline">
      <%= button_tag t('buttons.cancel'), type: "submit", 
        name: "cancel", value: true, class: 'btn btn-secondary' %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<body>
  <div class="container">
    <div class="row justify-content-center">
      <div class="main-content">
        <h3>User List</h3>
        <%= form_tag(search_path, :method => "get", class: "row mb-2 ms-5") do %>
        <div class="col-md-2">
          <%= search_field_tag :search, params[:search], class: "form-control", placeholder: "Name" %>
        </div>
        <div class="col-md-2">
          <%= search_field_tag :search, params[:search], class: "form-control", placeholder: "Email" %>
        </div>

        <div class="col-md-3 row">
          <label class="col-form-label col-md-3">From:</label>
          <div class="col-md-8">
            <%= date_field_tag :start_date, params[:search], class: "form-control" %>
          </div>
        </div>

        <div class="col-md-3 row">
          <label class="col-form-label col-md-2">To:</label>
          <div class="col-md-8">
            <%= date_field_tag :end_date, params[:search], class: "form-control" %>
          </div>
        </div>

        <div class="col-md-2 row">
          <%= button_tag "Search", class: "btn btn-success" %>
        </div>
        <% end %>
        <div class="scrollme">
          <table id="user-table" class="table table-responsive my-tab display nowrap" style="width:100%">
            <thead class="thead-custom">
              <tr>
                <th class="col-w">No</th>
                <th class="col-w">Name</th>
                <th class="col-w">Email</th>
                <th class="col-w">Created User</th>
                <th class="col-w">Type</th>
                <th class="col-w">Phone</th>
                <th class="col-w">Date of Birth</th>
                <th class="col-w">Address</th>
                <th class="col-w">Created_date</th>
                <th class="col-w">Updated_date</th>
                <th class="col-w">Operation</th>
              </tr>
            </thead>
            <tbody>
              <% index = 1 %>
              <% @user.each do |user| %>
              <tr>
                <td class="col-w mycol"> <%= index %> </td>
                <td class="col-w"> <%= user.name %> </td>
                <td class="col-w"> <%= user.email %> </td>
                <td class="col-w"> <%= user.create_user_id %> </td>
                <td class="col-w">
                  <%  if user.type == '0' %>
                  Admin
                  <% elsif user.type == '1' %>
                  User
                  <% end %>
                </td>
                <td class="col-w"> <%= user.phone %> </td>
                <td class="col-w"> <%= user.dob.strftime('%F').gsub('-', '/') %> </td>
                <td class="col-w"> <%= user.address %> </td>
                <td class="col-w"> <%= user.created_at.strftime('%F').gsub('-', '/') %> </td>
                <td class="col-w"> <%= user.updated_at.strftime('%F').gsub('-', '/') %> </td>
                <td class="col-w">
                  edit
                </td>
              </tr>
              <% index += 1 %>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</body>
<script type="text/javascript">
  $(document).ready(function () {
    $('#user-table').DataTable({
      "pagingType": "simple_numbers",
      "pageLength": 5,
      "ordering": false,
      "info": false,
      "lengthChange": false,
      "bFilter": false,
      "scrollX": true
    })
  });
</script>

app/views/users/new.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="main-content">
      <h3>Register</h3>
      <div class="col-6">
        <%= form_with scope: :user, url: "/users/confirm",:html => {:id => "user-new"}, local: true do |form| %>
        <div class="form-group row">
          <%= form.label :name, class: 'col-sm-2 col-form-label' %>
          <div class="col-sm-10">
            <%= form.text_field :name, class: 'form-control', required: true %>
          </div>
        </div>

        <div class="form-group row">
          <%= form.label :email, class: 'col-sm-2 col-form-label' %>
          <div class="col-sm-10">
            <%= form.text_field :email, class: 'form-control' %>
          </div>
        </div>

        <div class="form-group row">
          <%= form.label :password, class: 'col-sm-2 col-form-label' %>
          <div class="col-sm-10">
            <%= form.password_field :password, class: 'form-control' %>
          </div>
        </div>

        <div class="form-group row">
          <%= form.label :'Password confirmation', class: 'col-sm-2 col-form-label' %>
          <div class="col-sm-10">
            <%= form.password_field :password_confirmation, class: 'form-control' %>
          </div>
        </div>

        <div class="form-group row">
          <%= form.label :type, class: 'col-sm-2 col-form-label' %>
          <div class="col-sm-10">
          <%= form.select :type, [['Admin',0],['User',1]], {}, {class: "form-select"} %>
          </div>
        </div>

        <div class="form-group row">
          <%= form.label :phone, class: 'col-sm-2 col-form-label' %>
          <div class="col-sm-10">
            <%= form.text_field :phone, class: 'form-control' %>
          </div>
        </div>

        <div class="form-group row">
          <%= form.label :dob, class: 'col-sm-2 col-form-label' %>
          <div class="col-sm-10">
            <%= form.text_field :dob, class: 'form-control' %>
          </div>
        </div>

        <div class="form-group row">
          <%= form.label :address, class: 'col-sm-2 col-form-label' %>
          <div class="col-sm-10">
            <%= form.text_field :address, class: 'form-control' %>
          </div>
        </div>

        <div class="form-group row">
          <%= form.label :profile, class: 'col-sm-2 col-form-label' %>
          <div class="col-sm-10">
            <%= form.text_field :profile, class: 'form-control' %>
          </div>
        </div>

        <div class="form-group">
          <%= form.submit "Register", class: 'form-control btn-primary' %>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>